/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).
Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: cfde1c11-1e8c-4ed5-bde6-6a792efec4bf
To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/
import Mathlib
set_option linter.mathlibStandardSet false
open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise
set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128
set_option relaxedAutoImplicit false
set_option autoImplicit false
noncomputable section
/-
If a finite magma satisfies (A), then it is left cancellative.
-/
def PropA (M : Type*) [Mul M] : Prop := ∀ x y : M, x = y * (x * ((y * x) * y))
def PropB (M : Type*) [Mul M] : Prop := ∀ x : M, x = ((x * x) * x) * x
theorem left_cancellative_of_PropA {M : Type*} [Mul M] [Finite M] (h : PropA M) :
  ∀ c x y : M, c * x = c * y → x = y := by
    intro c x y hxy;
    -- For any fixed y, the map L_y : x ↦ y * x is surjective because for any x, x = y * (x * ((y * x) * y)).
    have h_surjective : ∀ y : M, Function.Surjective (fun x => y * x) := by
      intro y x
      obtain ⟨z, hz⟩ : ∃ z : M, x = y * z := by
        exact ⟨ _, h x y ⟩;
      exact ⟨ z, hz.symm ⟩;
    exact Finite.injective_iff_surjective.mpr ( h_surjective c ) hxy
/-
Search for a counterexample of size 3.
-/
def checkA (mul : Fin 3 → Fin 3 → Fin 3) : Bool :=
  List.all (List.product (List.finRange 3) (List.finRange 3)) fun (x, y) =>
    x == mul y (mul x (mul (mul y x) y))
def checkB (mul : Fin 3 → Fin 3 → Fin 3) : Bool :=
  List.all (List.finRange 3) fun x =>
    x == mul (mul (mul (mul x x) x) x) x -- Wait, (B) is x = ((x * x) * x) * x.
    -- Let's re-read (B): x = ((x ⋄ x) ⋄ x) ⋄ x.
    -- That is mul (mul (mul x x) x) x. Correct.
def findCounterexample : Option (Fin 3 → Fin 3 → Fin 3) :=
  let tables := List.replicate 9 (List.finRange 3) |> List.mapM id
  -- This generates all lists of length 9 with elements in Fin 3.
  -- We need to convert list to function.
  -- 3^9 is ~20k. mapM id on replicate 9 is generating the product.
  -- Wait, List.mapM id (List.replicate 9 (List.finRange 3)) generates all sequences.
  -- Let's be careful with the order.
  -- A table is Fin 3 -> Fin 3 -> Fin 3.
  -- We can map index (i, j) to 3*i + j.
  let toTable (l : List (Fin 3)) : Fin 3 → Fin 3 → Fin 3 :=
    fun i j => l.get! (3 * i.val + j.val)
  let candidates := List.mapM (fun _ => List.finRange 3) (List.range 9)
  candidates.findSome? fun l =>
    let mul := toTable l
    if checkA mul && !checkB mul then some mul else none
#eval findCounterexample
/-
Check for models of size 2.
-/
def checkSingleton (mul : Fin 2 → Fin 2 → Fin 2) : Bool :=
  List.all (List.finRange 2) fun x =>
    List.all (List.finRange 2) fun y => x == y
def findModelSize2 : List (Fin 2 → Fin 2 → Fin 2) :=
  let candidates := List.replicate 4 (List.finRange 2) |> List.mapM id
  let toTable (l : List (Fin 2)) : Fin 2 → Fin 2 → Fin 2 :=
    fun i j => l.get! (2 * i.val + j.val)
  candidates.filterMap fun l =>
    let mul := toTable l
    if List.all (List.product (List.finRange 2) (List.finRange 2)) (fun (x, y) =>
      x == mul y (mul x (mul (mul y x) y))) then some mul else none
#eval findModelSize2.length
#eval findModelSize2.all checkSingleton
/-
Check if x = x * u holds.
-/
def checkXMulU (mul : Fin 3 → Fin 3 → Fin 3) : Bool :=
  List.all (List.finRange 3) fun x =>
    x == mul x (mul (mul x x) x)
def findCounterexampleXMulU : Option (Fin 3 → Fin 3 → Fin 3) :=
  let candidates := List.replicate 9 (List.finRange 3) |> List.mapM id
  let toTable (l : List (Fin 3)) : Fin 3 → Fin 3 → Fin 3 :=
    fun i j => l.get! (3 * i.val + j.val)
  candidates.findSome? fun l =>
    let mul := toTable l
    if checkA mul && !checkXMulU mul then some mul else none
#eval findCounterexampleXMulU
/-
Analyze models of size 3.
-/
def checkIdempotent (mul : Fin 3 → Fin 3 → Fin 3) : Bool :=
  List.all (List.finRange 3) fun x => x == mul x x
def checkCommutative (mul : Fin 3 → Fin 3 → Fin 3) : Bool :=
  List.all (List.product (List.finRange 3) (List.finRange 3)) fun (x, y) => mul x y == mul y x
def checkAssociative (mul : Fin 3 → Fin 3 → Fin 3) : Bool :=
  List.all (List.product (List.product (List.finRange 3) (List.finRange 3)) (List.finRange 3))
    fun ((x, y), z) => mul (mul x y) z == mul x (mul y z)
def checkB_Correct (mul : Fin 3 → Fin 3 → Fin 3) : Bool :=
  List.all (List.finRange 3) fun x =>
    let x2 := mul x x
    let x3 := mul x2 x
    let x4 := mul x3 x
    x == x4
def analyzeSize3 : String :=
  let candidates := List.replicate 9 (List.finRange 3) |> List.mapM id
  let toTable (l : List (Fin 3)) : Fin 3 → Fin 3 → Fin 3 :=
    fun i j => l.get! (3 * i.val + j.val)
  let models := candidates.filterMap fun l =>
    let mul := toTable l
    if checkA mul then some mul else none
  let count := models.length
  let idem := models.all checkIdempotent
  let comm := models.all checkCommutative
  let assoc := models.all checkAssociative
  let b_holds := models.all checkB_Correct
  s!"Count: {count}, Idem: {idem}, Comm: {comm}, Assoc: {assoc}, B_holds: {b_holds}"
#eval analyzeSize3
/-
Define the inverse of left multiplication and prove it is a two-sided inverse.
-/
def inv_L {M : Type*} [Mul M] (y : M) (x : M) : M := x * ((y * x) * y)
theorem inv_L_is_right_inverse {M : Type*} [Mul M] (h : PropA M) (y : M) :
  Function.RightInverse (inv_L y) (HMul.hMul y) := by
  intro x
  exact (h x y).symm
theorem inv_L_is_left_inverse {M : Type*} [Mul M] [Finite M] (h : PropA M) (y : M) :
  Function.LeftInverse (inv_L y) (HMul.hMul y) := by
  have h_surj : Function.Surjective (HMul.hMul y) :=
    Function.RightInverse.surjective (inv_L_is_right_inverse h y)
  have h_inj : Function.Injective (HMul.hMul y) :=
    Finite.injective_iff_surjective.mpr h_surj
  exact Function.RightInverse.leftInverse_of_injective (inv_L_is_right_inverse h y) h_inj
/-
Define L_perm.
-/
noncomputable def L_perm {M : Type*} [Mul M] [Finite M] (h : PropA M) (x : M) : Equiv.Perm M :=
  Equiv.ofBijective (fun z => x * z) (by
    have h_inj : Function.Injective (fun z => x * z) := left_cancellative_of_PropA h x
    have h_surj : Function.Surjective (fun z => x * z) := Finite.injective_iff_surjective.mp h_inj
    exact ⟨h_inj, h_surj⟩
  )
theorem L_perm_apply {M : Type*} [Mul M] [Finite M] (h : PropA M) (x y : M) :
  L_perm h x y = x * y := rfl
/-
Check types of Nat.iterate and Equiv.Perm.coe_pow.
-/
#check Nat.iterate
#check Equiv.Perm.coe_pow
/-
Prove L_perm power property.
-/
theorem L_perm_pow_apply {M : Type*} [Mul M] [Finite M] (h : PropA M) (x : M) (n : ℕ) (y : M) :
  ((L_perm h x)^n) y = (HMul.hMul x)^[n] y := by
    exact?
/-
Prove the inverse formula for L_perm.
-/
theorem L_perm_inv_apply {M : Type*} [Mul M] [Finite M] (h : PropA M) (x y : M) :
  (L_perm h x).symm y = y * ((x * y) * x) := by
  apply (L_perm h x).injective
  rw [Equiv.apply_symm_apply, L_perm_apply]
  exact h y x
/-
Search for a counterexample of size 4.
-/
def findCounterexampleSize4 : Option (Fin 4 → Fin 4 → Fin 4) :=
  let n := 4
  let range := List.finRange n
  let perms := (List.permutations range)
  -- We need 4 rows, each is a permutation.
  -- There are 24^4 = 331,776 candidates.
  let candidates := List.replicate n perms |> List.mapM id
  let toTable (rows : List (List (Fin 4))) : Fin 4 → Fin 4 → Fin 4 :=
    fun i j => (rows.get! i.val).get! j.val
  candidates.findSome? fun rows =>
    let mul := toTable rows
    -- Check (A): x = y * (x * ((y * x) * y))
    let checkA := range.all fun x => range.all fun y =>
      x == mul y (mul x (mul (mul y x) y))
    if checkA then
      -- Check (B): x = ((x * x) * x) * x
      let checkB := range.all fun x =>
        x == mul (mul (mul x x) x) x
      if !checkB then some mul else none
    else none
#eval findCounterexampleSize4.isSome
/-
Check if affine models satisfy (B).
-/
theorem affine_model_implication {F : Type*} [Field F] [CharP F 2] (a b : F)
  (h_poly : b^8 + b^4 + b^2 + b + 1 = 0)
  (h_a : a * b * (1 + b^2) = 1) :
  a^3 + a^2 * b + a * b + b = 1 := by
    grind
/-
Search for counterexample of size 5.
-/
def checkA_list (n : Nat) (mul : List (List Nat)) : Bool :=
  let range := List.range n
  range.all fun x => range.all fun y =>
    let yx := (mul.get! y).get! x
    let yx_y := (mul.get! yx).get! y
    let x_yx_y := (mul.get! x).get! yx_y
    let rhs := (mul.get! y).get! x_yx_y
    x == rhs
def checkB_list (n : Nat) (mul : List (List Nat)) : Bool :=
  let range := List.range n
  range.all fun x =>
    let x2 := (mul.get! x).get! x
    let x3 := (mul.get! x2).get! x
    let x4 := (mul.get! x3).get! x
    x == x4
def solve_size_5 : Option (List (List Nat)) :=
  let n := 5
  let range := List.range n
  let perms := (List.permutations range)

  -- We use a fuel parameter to satisfy the termination checker
  let rec solve (rows : List (List Nat)) (fuel : Nat) : Option (List (List Nat)) :=
    match fuel with
    | 0 => none
    | fuel + 1 =>
      if rows.length == n then
        if checkA_list n rows && !checkB_list n rows then some rows else none
      else
        let k := rows.length
        -- Try to find a valid next row
        perms.findSome? fun p =>
          -- Check consistency with existing rows
          -- For each i < k, check the cross constraints
          let consistent := (List.zip (List.range k) rows).all fun (i, row_i) =>
            -- Constraint: pi_k(pi_i^2(k)) == pi_i^{-1}(k)
            -- And: pi_i(pi_k^2(i)) == pi_k^{-1}(i)
            let inv_p (y : Nat) := range.find? (fun x => p.get! x == y) |> Option.get!
            let inv_row_i (y : Nat) := range.find? (fun x => row_i.get! x == y) |> Option.get!
            let sq_p (x : Nat) := p.get! (p.get! x)
            let sq_row_i (x : Nat) := row_i.get! (row_i.get! x)

            let c1 := p.get! (sq_row_i k) == inv_row_i k
            let c2 := row_i.get! (sq_p i) == inv_p i
            c1 && c2

          -- Also check self-consistency for row k: pi_k(pi_k^2(k)) == pi_k^{-1}(k)
          let self_consistent :=
            let inv_p (y : Nat) := range.find? (fun x => p.get! x == y) |> Option.get!
            let sq_p (x : Nat) := p.get! (p.get! x)
            p.get! (sq_p k) == inv_p k

          if consistent && self_consistent then
            solve (rows ++ [p]) fuel
          else none
  solve [] (n + 1)
#eval solve_size_5
/-
Search for affine counterexample over GF(8).
-/
def mul_GF8_table : List (List Nat) :=
  [[0, 0, 0, 0, 0, 0, 0, 0],
   [0, 1, 2, 3, 4, 5, 6, 7],
   [0, 2, 4, 6, 3, 1, 7, 5],
   [0, 3, 6, 5, 7, 4, 1, 2],
   [0, 4, 3, 7, 6, 2, 5, 1],
   [0, 5, 1, 4, 2, 7, 3, 6],
   [0, 6, 7, 1, 5, 3, 2, 4],
   [0, 7, 5, 2, 1, 6, 4, 3]]
def mul_GF8 (x y : Nat) : Nat :=
  (mul_GF8_table.get! x).get! y
def add_GF8 (x y : Nat) : Nat :=
  x.xor y
def checkAffineA (a b : Nat) : Bool :=
  let range := List.range 8
  range.all fun x => range.all fun y =>
    -- x = y * (x * ((y * x) * y))
    -- in affine: x = a*y + b*(a*x + b*(a*(a*y + b*x) + b*y))
    -- Let's compute it using the operations
    let yx := add_GF8 (mul_GF8 a y) (mul_GF8 b x)
    let yx_y := add_GF8 (mul_GF8 a yx) (mul_GF8 b y)
    let x_yx_y := add_GF8 (mul_GF8 a x) (mul_GF8 b yx_y)
    let rhs := add_GF8 (mul_GF8 a y) (mul_GF8 b x_yx_y)
    x == rhs
def checkAffineB (a b : Nat) : Bool :=
  let range := List.range 8
  range.all fun x =>
    -- x = ((x * x) * x) * x
    let x2 := add_GF8 (mul_GF8 a x) (mul_GF8 b x)
    let x3 := add_GF8 (mul_GF8 a x2) (mul_GF8 b x)
    let x4 := add_GF8 (mul_GF8 a x3) (mul_GF8 b x)
    x == x4
def findAffineCounterexample : Option (Nat × Nat) :=
  let range := List.range 8
  range.findSome? fun a =>
    range.findSome? fun b =>
      if checkAffineA a b && !checkAffineB a b then some (a, b) else none
#eval findAffineCounterexample
/-
Search for counterexample of size 5 (corrected).
-/
def solve_size_5_corrected : Option (List (List Nat)) :=
  let n := 5
  let range := List.range n
  let perms := (List.permutations range)

  let rec solve (rows : List (List Nat)) (fuel : Nat) : Option (List (List Nat)) :=
    match fuel with
    | 0 => none
    | fuel + 1 =>
      if rows.length == n then
        if checkA_list n rows && !checkB_list n rows then some rows else none
      else
        let k := rows.length
        -- Try to find a valid next row p (which is L_k)
        perms.findSome? fun p =>
          -- Precompute inverse of p
          let inv_p (y : Nat) := range.find? (fun x => p.get! x == y) |> Option.get!

          -- Check self-constraint: p^4(k) == k
          let p_k := p.get! k
          let p2_k := p.get! p_k
          let p3_k := p.get! p2_k
          let p4_k := p.get! p3_k
          let self_ok := p4_k == k

          if !self_ok then none
          else
            -- Check constraints with previous rows
            let consistent := (List.zip (List.range k) rows).all fun (i, row_i) =>
              let inv_row_i (y : Nat) := range.find? (fun x => row_i.get! x == y) |> Option.get!

              -- Constraint 1: L_k (L_{i*k} i) = L_i^{-1} k
              -- z = i * k = row_i k
              let z := row_i.get! k
              let c1 :=
                if z < k then
                  -- L_z is known (row_z)
                  let row_z := rows.get! z
                  p.get! (row_z.get! i) == inv_row_i k
                else if z == k then
                  -- L_z is p
                  p.get! (p.get! i) == inv_row_i k
                else
                  true -- Constraint on future row z

              -- Constraint 2: L_i (L_{k*i} k) = L_k^{-1} i
              -- w = k * i = p i
              let w := p.get! i
              let c2 :=
                if w < k then
                  -- L_w is known (row_w)
                  let row_w := rows.get! w
                  row_i.get! (row_w.get! k) == inv_p i
                else if w == k then
                  -- L_w is p
                  row_i.get! (p.get! k) == inv_p i
                else
                  true -- Constraint on future row w

              c1 && c2

            if consistent then
              solve (rows ++ [p]) fuel
            else none
  solve [] (n + 1)
#eval solve_size_5_corrected
/-
Prove L_{x^2} x = L_x^{-2} x.
-/
theorem L_sq_eq_L_inv_sq {M : Type*} [Mul M] [Finite M] (h : PropA M) (x : M) :
  L_perm h (x * x) x = (L_perm h x).symm ((L_perm h x).symm x) := by
  -- x = x * (x * ((x * x) * x))
  -- x = L_x (L_x (L_{x^2} x))
  -- L_x^{-1} (L_x^{-1} x) = L_{x^2} x
  have h_eq := h x x
  apply (L_perm h x).injective
  apply (L_perm h x).injective
  rw [Equiv.apply_symm_apply, Equiv.apply_symm_apply]
  exact h_eq.symm
/-
Count models of small sizes.
-/
def countModels (n : Nat) : Nat :=
  let range := List.range n
  let perms := (List.permutations range)

  let rec solve (rows : List (List Nat)) (fuel : Nat) : Nat :=
    match fuel with
    | 0 => 0
    | fuel + 1 =>
      if rows.length == n then
        -- Check (A)
        let checkA := range.all fun x => range.all fun y =>
          let mul (i j : Nat) := (rows.get! i).get! j
          x == mul y (mul x (mul (mul y x) y))
        if checkA then 1 else 0
      else
        let k := rows.length
        -- Try all permutations for the next row
        perms.foldl (fun count p =>
          -- Check consistency with existing rows
          let consistent := (List.zip (List.range k) rows).all fun (i, row_i) =>
            let inv_p (y : Nat) := range.find? (fun x => p.get! x == y) |> Option.get!
            let inv_row_i (y : Nat) := range.find? (fun x => row_i.get! x == y) |> Option.get!
            let sq_p (x : Nat) := p.get! (p.get! x)
            let sq_row_i (x : Nat) := row_i.get! (row_i.get! x)

            let c1 := p.get! (sq_row_i k) == inv_row_i k
            let c2 := row_i.get! (sq_p i) == inv_p i
            c1 && c2

          let self_consistent :=
            let inv_p (y : Nat) := range.find? (fun x => p.get! x == y) |> Option.get!
            let sq_p (x : Nat) := p.get! (p.get! x)
            p.get! (sq_p k) == inv_p k

          if consistent && self_consistent then
            count + solve (rows ++ [p]) fuel
          else count
        ) 0
  solve [] (n + 1)
#eval countModels 1
#eval countModels 2
#eval countModels 3
#eval countModels 4
